AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template deploys a SG
Parameters:
    VpcCIDR:
        Description: Please enter the IP range (CIDR notation) for this VPC
        Type: String
        Default: 10.192.0.0/16
        AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            EnableDnsSupport: true
            EnableDnsHostnames: true
            CidrBlock: !Ref VpcCIDR
            Tags:
                - Key: Name
                  Value: github-vpc
    SG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: "Traffic into CloudFormation"
        SecurityGroupIngress:
        -
            IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: "0.0.0.0/0"
        VpcId: !Ref VPC
        Tags:
          -
            Key: Name
            Value: github-SG
