AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template deploys a SG
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            EnableDnsSupport: true
            EnableDnsHostnames: true
            CidrBlock: "10.192.0.0/16"
            Tags:
                - Key: Name
                  Value: github-vpc
    SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: Allow http to client host
          VpcId: !Ref VPC
          SecurityGroupIngress:
          -
              Description: Allow inbound traffic to ElasticSearch from VPC CIDR
              IpProtocol: tcp
              FromPort: 443
              ToPort: 443
              CidrIp: "10.192.1.0/32"
          SecurityGroupEgress:
          -
              Description: Allow outbound traffic to ElasticSearch from VPC CIDR
              IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: "10.192.1.0/32"          
          Tags:
            -
              Key: Name
              Value: github-SG           
