---
name: "CloudFormation Stack Deploy"

# Triggered on all manual
# Triggered on all manual
on: push

env:

  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
  CFN_DIR: cloudformation

jobs:

  stackset-deploy:
    if: github.ref == 'refs/heads/master'
    name: CloudFormation StackSet Deploy
    runs-on: ubuntu-latest
    container:
      image: rosswickman/awspscore
    steps:
      - uses: actions/checkout@v2
      - uses: CFT-AUTOMATION/cicd-stack/deploy@master
        env:
         AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
